import { expect, test } from '@playwright/test';

const overview = 'Your 3×3 decision overview';

test('Find a robot is one four-step flow with the matrix only at the end of step four', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Better work. Start with one job.' })).toBeVisible();
  await expect(page.getByRole('button', { name: /^Explore job:/ })).toHaveCount(8);
  await expect(page.locator('[data-priority-cell], [data-cluster]')).toHaveCount(0);
  await expect(page.getByRole('form', { name: 'Robot requirements' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Factory', exact: true }).click();
  await page.getByRole('button', { name: 'Explore job: Inspect a site or equipment', exact: true }).click();
  await expect(page).toHaveURL(/step=1/);
  await expect(page.getByLabel('Work setting', { exact: true })).toHaveValue('factory');
  await page.getByLabel('Opportunity name').fill('Inspect assembly equipment');
  await page.getByText('Add working requirements', { exact: true }).click();
  await expect(page.getByLabel('Ground', { exact: true })).toHaveValue('');
  await expect(page.getByLabel('Exposure', { exact: true })).toHaveValue('');
  await page.getByLabel('Carried load (kg)', { exact: false }).fill('5');
  await expect(page.getByRole('region', { name: overview })).toHaveCount(0);
  const response = page.waitForResponse((res) => res.url().endsWith('/api/plan') && res.request().method() === 'POST');
  await page.getByRole('button', { name: 'Explore solutions', exact: true }).click();
  expect((await response).ok()).toBe(true);
  await expect(page).toHaveURL(/step=2/);
  const candidate = page.getByRole('article').first();
  await expect(candidate).toBeVisible();
  const robotName = await candidate.getByRole('heading').innerText();
  await candidate.getByRole('button', { name: 'Add to assessment', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Comparison for your job' })).toContainText(robotName);
  await expect(page.getByRole('region', { name: overview })).toHaveCount(0);
  await page.getByRole('button', { name: 'Estimate costs →' }).click();
  await expect(page).toHaveURL(/step=3/);
  await expect(page.getByText('Complete all five cost inputs', { exact: false })).toBeVisible();
  await expect(page.getByRole('region', { name: overview })).toHaveCount(0);
  await page.getByRole('button', { name: 'Prepare pilot brief →' }).click();
  await expect(page).toHaveURL(/step=4/);
  await page.getByLabel('Business value', { exact: true }).selectOption('high');
  await page.getByLabel('Deployment readiness', { exact: true }).selectOption('medium');
  await page.getByLabel('Why this position?').fill('Useful inspection task; site integration needs confirmation.');
  const matrix = page.getByRole('region', { name: overview });
  await expect(matrix.locator('[data-priority-cell]')).toHaveCount(9);
  await expect(matrix.locator('[data-priority-cell="high:medium"]')).toContainText('Inspect assembly equipment');
  await expect(matrix.locator('[data-priority-cell="high:medium"]')).toContainText(robotName);
  expect(await matrix.evaluate((element) => Boolean((document.querySelector('[data-plan-brief]')?.compareDocumentPosition(element) ?? 0) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true);
  await page.reload();
  await expect(page.getByLabel('Why this position?')).toHaveValue('Useful inspection task; site integration needs confirmation.');
  await page.getByRole('button', { name: '2. Solutions', exact: true }).click();
  await expect(page.getByRole('region', { name: overview })).toHaveCount(0);
  await expect(page).toHaveURL(/step=2/);
  await page.goBack();
  await expect(page).toHaveURL(/step=4/);
  await expect(matrix).toBeVisible();
  expect(errors).toEqual([]);
});

test('returning to the homepage offers the saved draft without showing the workspace or matrix', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Start with my job', exact: true }).click();
  await page.getByLabel('Opportunity name').fill('My factory inquiry');
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Continue assessment', exact: false })).toBeVisible();
  await expect(page.getByRole('navigation', { name: 'Find a robot steps' })).toHaveCount(0);
  await expect(page.getByRole('region', { name: overview })).toHaveCount(0);
  await page.getByRole('button', { name: 'Continue assessment', exact: false }).click();
  await expect(page.getByLabel('Opportunity name')).toHaveValue('My factory inquiry');
  await page.getByRole('button', { name: '4. Pilot brief', exact: true }).click();
  const matrix = page.getByRole('region', { name: overview });
  await expect(matrix).toContainText('Not yet assessed');
  await expect(matrix.locator('[data-priority-cell] button')).toHaveCount(0);
});

test('the finder landing and final matrix stay clean on desktop and mobile', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Factory', exact: true })).toBeEnabled();
  await page.screenshot({ path: '.out/finder-home-dark.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Warehouse & yard', exact: true }).click();
  await page.locator('#matcher').evaluate((element) => window.scrollTo({ top: element.getBoundingClientRect().top + window.scrollY - 85, behavior: 'instant' }));
  await page.screenshot({ path: '.out/finder-dark-desktop.png', animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '.out/finder-home-mobile.png', animations: 'disabled' });
  await page.getByRole('button', { name: 'Explore job: Capture construction progress', exact: true }).click();
  await expect(page.getByLabel('Work setting', { exact: true })).toHaveValue('yard');
  await page.screenshot({ path: '.out/finder-step-one-mobile.png', animations: 'disabled' });
  await page.getByRole('button', { name: '4. Pilot brief', exact: true }).click();
  await page.getByLabel('Business value', { exact: true }).selectOption('medium');
  await page.getByLabel('Deployment readiness', { exact: true }).selectOption('low');
  const matrix = page.getByRole('region', { name: overview });
  await expect(matrix.locator('[data-priority-cell]')).toHaveCount(9);
  await matrix.evaluate((element) => window.scrollTo({ top: element.getBoundingClientRect().top + window.scrollY - 120, behavior: 'instant' }));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '.out/finder-final-matrix-mobile.png', animations: 'disabled' });
});