// Generated by npm run research:sync.
import opportunityBatch0 from '@/data/discovery-opportunities/humanoids-h2.json';
import opportunityBatch1 from '@/data/discovery-opportunities/humanoids-logistics.json';
import opportunityBatch2 from '@/data/discovery-opportunities/humanoids-production.json';
import opportunityBatch3 from '@/data/discovery-opportunities/humanoids-research.json';
import opportunityBatch4 from '@/data/discovery-opportunities/humanoids-tron.json';
import opportunityBatch5 from '@/data/discovery-opportunities/loop-01.json';
import opportunityBatch6 from '@/data/discovery-opportunities/loop-02.json';
import opportunityBatch7 from '@/data/discovery-opportunities/loop-03.json';
import opportunityBatch8 from '@/data/discovery-opportunities/loop-05.json';
import opportunityBatch9 from '@/data/discovery-opportunities/loop-07.json';
import opportunityBatch10 from '@/data/discovery-opportunities/loop-08.json';
import opportunityBatch11 from '@/data/discovery-opportunities/loop-09.json';
import opportunityBatch12 from '@/data/discovery-opportunities/loop-10.json';
import { RESEARCHED_OPPORTUNITIES } from './researched';
import type { OpportunitySeed } from './model';
export type ResearchedTask = Pick<OpportunitySeed, 'id' | 'title' | 'summary' | 'industries' | 'family' | 'setting' | 'reviewLinks'>;
export const RESEARCHED_TASKS = [ ...RESEARCHED_OPPORTUNITIES, ...opportunityBatch0.opportunities, ...opportunityBatch1.opportunities, ...opportunityBatch2.opportunities, ...opportunityBatch3.opportunities, ...opportunityBatch4.opportunities, ...opportunityBatch5.opportunities, ...opportunityBatch6.opportunities, ...opportunityBatch7.opportunities, ...opportunityBatch8.opportunities, ...opportunityBatch9.opportunities, ...opportunityBatch10.opportunities, ...opportunityBatch11.opportunities, ...opportunityBatch12.opportunities] as ResearchedTask[];
