// Generated by npm run research:sync from reviewed JSON batches.
import batch0 from '@/data/discovery-links/construction-assembly.json';
import batch1 from '@/data/discovery-links/construction-finishing.json';
import batch2 from '@/data/discovery-links/indoor-transport.json';
import batch3 from '@/data/discovery-links/loop-01.json';
import batch4 from '@/data/discovery-links/loop-02.json';
import batch5 from '@/data/discovery-links/loop-03.json';
import batch6 from '@/data/discovery-links/loop-04.json';
import batch7 from '@/data/discovery-links/loop-05.json';
import batch8 from '@/data/discovery-links/loop-06.json';
import batch9 from '@/data/discovery-links/loop-07.json';
import batch10 from '@/data/discovery-links/loop-08.json';
import batch11 from '@/data/discovery-links/loop-09.json';
import batch12 from '@/data/discovery-links/loop-10.json';
import batch13 from '@/data/discovery-links/production-handling.json';
import type { TaskReviewLink } from './links';
export const REVIEWED_TASK_LINKS = [...batch0.links, ...batch1.links, ...batch2.links, ...batch3.links, ...batch4.links, ...batch5.links, ...batch6.links, ...batch7.links, ...batch8.links, ...batch9.links, ...batch10.links, ...batch11.links, ...batch12.links, ...batch13.links] as TaskReviewLink[];
