import {readdirSync,readFileSync,writeFileSync,renameSync} from 'node:fs';
import {join} from 'node:path';
import {z} from 'zod';
import {TaskReviewLinkSchema} from '../lib/discovery/links';

// JSON stays authoritative; generate browser-safe imports without shipping node:fs to clients.
function sync(dir:string,property:'links'|'images',output:string,typeImport:string,typeName:string,exportName:string,schema:z.ZodType){
 const files=readdirSync(dir).filter(file=>file.endsWith('.json')).sort();
 const imports:string[]=[],spreads:string[]=[],seen=new Set<string>();
 for(const [index,file]of files.entries()){
  const batch=JSON.parse(readFileSync(join(dir,file),'utf8').replace(/^\uFEFF/,''));
  if(batch.schemaVersion!==1||!Array.isArray(batch[property]))throw Error('Bad research batch '+file);
  for(const raw of batch[property]){schema.parse(raw);const key=property==='images'?raw.reviewId:raw.taskId+':'+raw.reviewId;if(seen.has(key))throw Error('Duplicate '+property+' entry '+key);seen.add(key);}
  imports.push('import batch'+index+" from '@/"+dir+'/'+file+"';");spreads.push('...batch'+index+'.'+property);
 }
 const source='// Generated by npm run research:sync from reviewed JSON batches.\n'+imports.join('\n')+'\n'+typeImport+'\nexport const '+exportName+' = ['+spreads.join(', ')+'] as '+typeName+'[];\n';
 writeFileSync(output+'.tmp',source);renameSync(output+'.tmp',output);
 console.log(exportName+': '+seen.size+' entries from '+files.length+' batches');
}
sync('data/discovery-links','links','lib/discovery/task-links.ts',"import type { TaskReviewLink } from './links';",'TaskReviewLink','REVIEWED_TASK_LINKS',TaskReviewLinkSchema);
sync('data/discovery-media','images','lib/discovery/media-batches.ts','export type SourcedReviewImage = {reviewId:string;url:string;sourceUrl:string;alt:string;checkedAt:string};','SourcedReviewImage','SOURCED_REVIEW_IMAGES',z.object({reviewId:z.string().min(1),url:z.url().startsWith('https://'),sourceUrl:z.url().startsWith('https://'),alt:z.string().min(10),checkedAt:z.iso.date()}));
import { readdirSync as listFiles } from 'node:fs';
const opportunityFiles=listFiles('data/discovery-opportunities').filter(file=>file.endsWith('.json')).sort();
const opportunityImports=opportunityFiles.map((file,index)=>'import opportunityBatch'+index+" from '@/data/discovery-opportunities/"+file+"';");
const researchSource='// Generated by npm run research:sync.\n'+opportunityImports.join('\n')+`\nimport { RESEARCHED_OPPORTUNITIES } from './researched';
import type { OpportunitySeed } from './model';
export type ResearchedTask = Pick<OpportunitySeed, 'id' | 'title' | 'summary' | 'industries' | 'family' | 'setting' | 'reviewLinks'>;
export const RESEARCHED_TASKS = [ ...RESEARCHED_OPPORTUNITIES, `+opportunityFiles.map((_,i)=>'...opportunityBatch'+i+'.opportunities').join(', ')+'] as ResearchedTask[];\n';
writeFileSync('lib/discovery/researched-tasks.ts.tmp',researchSource);renameSync('lib/discovery/researched-tasks.ts.tmp','lib/discovery/researched-tasks.ts');
