import type { IndustryId } from '@/lib/content/industries';
import type { FamilyId, SolutionClassId } from '@/lib/content/vocab';
export const WORKFLOW_IDS = ['transport', 'machine_tending', 'inspection', 'floor_cleaning', 'drilling_fastening', 'layout_marking', 'material_handling', 'surface_finishing', 'picking_sorting', 'bricklaying', 'rebar_tying', 'demolition', 'welding', 'window_cleaning', 'agricultural_fieldwork', 'farm_operations', 'waste_sorting', 'robotics_research'] as const;
export type WorkflowId = (typeof WORKFLOW_IDS)[number];
export type Workflow = {
  id: WorkflowId; title: string; family: FamilyId; industries: IndustryId[]; summary: string; outcome: string;
  process: string[]; questions: string[]; pilot: string; alternatives: SolutionClassId[];
};
export const WORKFLOWS: Workflow[] = [
  { id: 'robotics_research', title: 'Develop and evaluate robot skills', family: 'robotics_research', industries: ['research_education'],
    summary: 'Collect demonstrations, train policies and evaluate motion or manipulation on an exact robot configuration in a supervised research workspace.',
    outcome: 'Reproducible experimental results with recorded software, hardware, intervention and failure conditions.',
    process: ['Specify the experiment and exact hardware', 'Configure sensing, software and supervision', 'Collect demonstrations or test the control policy', 'Record results, failures and recovery steps'],
    questions: ['Which robot, hands, sensors and software versions are included?', 'Does the published example run on physical hardware or only in simulation?', 'Who supervises the experiment and handles resets?', 'What measurement and failure criteria define the experiment?'],
    pilot: 'Reproduce a small documented experiment before expanding object sets or motion conditions. Record success rates, interventions, software versions and recovery effort; a research result does not establish industrial readiness.',
    alternatives: ['humanoid', 'mobile_manipulator_wheeled', 'quadruped_inspection', 'keep_process'] },
  { id: 'transport', title: 'Move materials between stations', family: 'intralogistics_transport', industries: ['manufacturing', 'warehousing', 'healthcare_logistics', 'retail_hospitality'],
    summary: 'Move loaded carts, shelves or containers between agreed handoff points. Define loading and unloading separately from travel.',
    outcome: 'Reliable material delivery with less total human travel and no increase in damaged or late loads.',
    process: ['Load and secure the carrier', 'Dispatch and navigate the agreed route', 'Dock, hand over and confirm receipt', 'Recover exceptions and recharge'],
    questions: ['What is the full moving mass, including the carrier and top module?', 'Which doors, lifts, aisles, gradients and mixed traffic are on the route?', 'Who loads and unloads, and how many trips per shift are required?', 'Which WMS, fleet and machine interfaces are required?'],
    pilot: 'Use one representative loaded carrier and route. Measure accepted deliveries, interventions, human minutes, delays and charging downtime against the current process.',
    alternatives: ['amr_carts', 'mobile_manipulator_wheeled', 'dedicated_machine', 'keep_process', 'process_change'] },
  { id: 'machine_tending', title: 'Load and unload a machine', family: 'machine_tending', industries: ['manufacturing'],
    summary: 'Transfer representative parts between a prepared station and a machine using an exact arm, gripper, fixtures and machine interface.',
    outcome: 'Accepted machine cycles with less repetitive handling and a documented exception process.',
    process: ['Present and identify the part', 'Grip and place it in the fixture', 'Exchange the machine-ready signal', 'Unload, check and route the finished part'],
    questions: ['What do the part, gripper and fixtures weigh, and where is their centre of gravity?', 'Which loaded reach, orientation, tolerances and cycle time are required?', 'How are doors, clamps and machine states integrated?', 'Which safeguards and human interventions does the complete cell require?'],
    pilot: 'Start with a mock or inactive station, then validate the integrated cell. Measure accepted cycles, changeover time, damaged parts and interventions with agreed stop criteria.',
    alternatives: ['fixed_cobot_cell', 'dedicated_machine', 'mobile_manipulator_wheeled', 'keep_process'] },
  { id: 'inspection', title: 'Inspect industrial assets on a route', family: 'inspection_qa_documentation', industries: ['energy', 'manufacturing', 'facilities'],
    summary: 'Collect repeatable visual, thermal or acoustic observations for a defined inspection task and response workflow.',
    outcome: 'Usable observations at the required frequency, with clear responsibility for reviewing and acting on findings.',
    process: ['Plan access and observation points', 'Navigate with the installed sensor payload', 'Capture and review the observations', 'Escalate findings and handle missed points'],
    questions: ['What must be detected, at what quality and with which calibrated sensor?', 'What are the route, stairs, access restrictions and environmental exposures?', 'Is operation teleoperated, supervised or autonomous in this configuration?', 'Who reviews results, and how are missed or false findings measured?'],
    pilot: 'Compare observations with a qualified person on a representative route. Measure usable coverage, missed findings, interventions and total capture-plus-review time.',
    alternatives: ['quadruped_inspection', 'dedicated_machine', 'keep_process', 'process_change'] },
  { id: 'floor_cleaning', title: 'Scrub a commercial floor', family: 'cleaning_housekeeping_replenishment', industries: ['facilities', 'warehousing', 'retail_hospitality'],
    summary: 'Clean an agreed floor area with a dedicated scrubber, including preparation, edges, waste water, consumables and recovery.',
    outcome: 'An accepted cleaning result with lower total operator effort across preparation, cleaning and maintenance.',
    process: ['Prepare the area and fill consumables', 'Clean accessible routes', 'Inspect edges and missed areas', 'Empty, clean and maintain the machine'],
    questions: ['Which floor, contaminants, chemicals and accepted finish define the task?', 'What aisle width, obstacles, ramps and public traffic must be handled?', 'Who handles preparation, refilling, waste water and exceptions?', 'What usable area and human minutes per shift are required?'],
    pilot: 'Test representative surfaces and operating windows against the existing cleaner. Measure accepted area, total human time, missed areas and interruptions. Clinical disinfection needs a separate assessment.',
    alternatives: ['dedicated_machine', 'keep_process', 'process_change'] },
  {"id":"drilling_fastening","title":"Drill, nail and fasten components","family":"assembly_fastening","industries":["construction","manufacturing"],"summary":"Position and execute a specified drilling or fastening operation using the required tool, digital layout and prepared workpiece.","outcome":"Accepted work with measured human effort, quality and intervention rates for the complete configured process.","process":["Prepare the layout and material","Position and secure the tool or workpiece","Drill or fasten using the specified process","Inspect location, depth and fastening quality"],"questions":["Which substrate, fastener and tolerance are required?","What access, tool loads and dust extraction does the installation require?","Who feeds, positions and checks the work?"],"pilot":"Trial representative work with the exact configuration. Measure accepted output, manual preparation, interventions and total cycle time against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"layout_marking","title":"Mark construction layouts","family":"layout_marking_surveying","industries":["construction"],"summary":"Transfer prepared digital layout lines to an accessible site floor with survey control and a human checking process.","outcome":"Accepted work with measured human effort, quality and intervention rates for the complete configured process.","process":["Prepare and validate the drawing","Establish survey control","Print accessible floor markings","Check alignment and complete missed areas"],"questions":["What survey accuracy and floor condition are required?","Who validates BIM or CAD inputs and control points?","Which obstacles, steps and areas require manual marking?"],"pilot":"Trial representative work with the exact configuration. Measure accepted output, manual preparation, interventions and total cycle time against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"material_handling","title":"Position and handle materials","family":"heavy_element_handling","industries":["construction","manufacturing","warehousing"],"summary":"Lift, feed or position defined materials with an exact handling system and agreed loading, transfer and unloading boundaries.","outcome":"Accepted work with measured human effort, quality and intervention rates for the complete configured process.","process":["Prepare and secure the load","Feed or lift through the defined path","Position and release the material","Confirm handover and recover exceptions"],"questions":["What are the complete load, dimensions and centre of gravity?","Which fixtures, exclusion zones and interfaces are required?","Who loads, unloads and handles exceptions?"],"pilot":"Trial representative work with the exact configuration. Measure accepted output, manual preparation, interventions and total cycle time against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"surface_finishing","title":"Prepare and coat surfaces","family":"surface_finishing","industries":["construction","manufacturing"],"summary":"Apply a defined sanding, joint-finishing or coating process to compatible surfaces, with human setup and quality acceptance.","outcome":"Accepted work with measured human effort, quality and intervention rates for the complete configured process.","process":["Prepare and protect the work area","Supply the specified finishing material","Apply or sand the accessible surface","Inspect finish and complete edges"],"questions":["Which substrate, material and finish are required?","What height, edges and obstacles need manual work?","Who supplies consumables, ventilates and cleans the system?"],"pilot":"Trial representative work with the exact configuration. Measure accepted output, manual preparation, interventions and total cycle time against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"picking_sorting","title":"Pick, sort and palletize items","family":"kitting_picking_sorting","industries":["manufacturing","warehousing"],"summary":"Identify, grasp and place compatible items with a configured perception, gripper and presentation system.","outcome":"Accepted work with measured human effort, quality and intervention rates for the complete configured process.","process":["Present and identify the item","Grasp and transfer","Place into the defined destination","Handle uncertain picks and replenishment"],"questions":["What item shapes, weights and packaging must be handled?","Which gripper, vision and WMS interfaces are included?","Who handles damaged, unknown or entangled items?"],"pilot":"Trial representative work with the exact configuration. Measure accepted output, manual preparation, interventions and total cycle time against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"bricklaying","title":"Place masonry blocks","family":"assembly_fastening","industries":["construction"],"summary":"Place compatible masonry units using an engineered handling and bonding process on a prepared construction site.","outcome":"Accepted work with measured human effort, quality and intervention rates for the complete configured process.","process":["Prepare structure and digital plan","Supply compatible blocks and bonding material","Position and place blocks","Inspect joints and complete interfaces"],"questions":["Which block system and structural design are approved for the project?","What reach, site access and weather limitations apply?","Who handles supply, cutting, reinforcement and acceptance?"],"pilot":"Trial representative work with the exact configuration. Measure accepted output, manual preparation, interventions and total cycle time against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"rebar_tying","title":"Handle and tie reinforcement","family":"assembly_fastening","industries":["construction","manufacturing"],"summary":"Tie or handle compatible reinforcement within the access and geometry limits of a dedicated system.","outcome":"Accepted work with measured human effort, quality and intervention rates for the complete configured process.","process":["Prepare reinforcement layout","Supply and position material","Tie accessible intersections","Inspect ties and complete excluded intersections"],"questions":["What bar spacing, diameters and tie geometry are required?","Which edge zones, obstructions and access limits apply?","Who places bars and checks reinforcement acceptance?"],"pilot":"Trial representative work with the exact configuration. Measure accepted output, manual preparation, interventions and total cycle time against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"demolition","title":"Break and remove building material","family":"machine_operation_dedicated","industries":["construction"],"summary":"Use a remotely controlled demolition machine with a specified attachment and a competent operator.","outcome":"Accepted work with measured human effort, quality and intervention rates for the complete configured process.","process":["Survey and isolate the work area","Position and connect the machine","Operate the attachment under human control","Remove debris and inspect the remaining structure"],"questions":["What structural survey and exclusion zones are required?","Which tool, power supply, access and floor loading apply?","Who controls the machine, suppresses dust and removes debris?"],"pilot":"Trial representative work with the exact configuration. Measure accepted output, manual preparation, interventions and total cycle time against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"welding","title":"Weld prepared assemblies","family":"assembly_fastening","industries":["manufacturing","construction"],"summary":"Execute qualified weld paths inside a configured cell with suitable fixtures, process equipment and human inspection.","outcome":"Accepted work with measured human effort, quality and intervention rates for the complete configured process.","process":["Prepare and fixture parts","Select and qualify the weld program","Weld within the safeguarded cell","Inspect welds and unload"],"questions":["Which joint, material and welding procedure are required?","Who supplies fixtures, process equipment and extraction?","How are variation, programming and weld acceptance handled?"],"pilot":"Trial representative work with the exact configuration. Measure accepted output, manual preparation, interventions and total cycle time against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"window_cleaning","title":"Clean glass and facade surfaces","family":"cleaning_housekeeping_replenishment","industries":["construction","facilities"],"summary":"Clean compatible glass or facade surfaces with a configured support, anchoring and recovery system.","process":["Survey surface and access","Install support and cleaning supply","Clean compatible surface sections","Inspect edges and recover the equipment"],"questions":["Which facade materials, joints, angles and obstacles must be handled?","What support, tether, anchoring and exclusion arrangements are required?","Who sets up, monitors, retrieves and maintains the system?"],"outcome":"Accepted task output with measured human effort and documented operating limits.","pilot":"Trial representative conditions with the exact configuration. Measure accepted output, interventions, quality and complete human effort against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"agricultural_fieldwork","title":"Automate defined field operations","family":"machine_operation_dedicated","industries":["agriculture"],"summary":"Carry out crop-specific seeding, weeding or treatment with compatible tools and field conditions.","process":["Plan crop rows and field boundaries","Set up crop-specific tooling","Operate under agreed supervision","Check crop result and recover exceptions"],"questions":["Which crop, growth stage, spacing and soil conditions apply?","Which tasks and tools are included in the exact configuration?","Who supervises field access, replenishment and exceptional conditions?"],"outcome":"Accepted task output with measured human effort and documented operating limits.","pilot":"Trial representative conditions with the exact configuration. Measure accepted output, interventions, quality and complete human effort against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"farm_operations","title":"Handle routine livestock-farm work","family":"cleaning_housekeeping_replenishment","industries":["agriculture"],"summary":"Automate a defined feed-handling or manure-removal step inside a compatible livestock building.","process":["Check barn route and animal access","Prepare feed or cleaning system","Run the defined handling task","Inspect results, refill and maintain"],"questions":["Does the system push, remix, deliver or remove material?","Which floors, barriers, feeding tables and animal movements are compatible?","Who handles installation, cleaning, recovery and service?"],"outcome":"Accepted task output with measured human effort and documented operating limits.","pilot":"Trial representative conditions with the exact configuration. Measure accepted output, interventions, quality and complete human effort against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
  {"id":"waste_sorting","title":"Sort materials from a waste stream","family":"kitting_picking_sorting","industries":["waste_recycling"],"summary":"Identify and pick supported fractions from a prepared waste stream using a configured sorting line.","process":["Characterize and present waste","Detect and classify supported fractions","Pick into defined destinations","Measure recovery, purity and exceptions"],"questions":["What material, contamination, throughput and size distribution apply?","Which conveyors, sensing, grippers and fractions are configured?","How are missed picks, purity and maintenance measured?"],"outcome":"Accepted task output with measured human effort and documented operating limits.","pilot":"Trial representative conditions with the exact configuration. Measure accepted output, interventions, quality and complete human effort against the current process.","alternatives":["dedicated_machine","keep_process","process_change"]},
];
export const workflowById = (id: string) => WORKFLOWS.find((w) => w.id === id);
export const workflowsForFamily = (family: string) => WORKFLOWS.filter((w) => w.family === family);

